routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('layout.utama');
});*/

Route::get('/', 'UtamaController@index');


Route::get('/utama', function () {
    return view('layout.utama');
});

Route::get('ttg', 'UtamaController@tentang');
Route::get('kacamata', 'UtamaController@kacamata');
Route::get('contactlense', 'UtamaController@contactlense');
Route::get('contact', 'UtamaController@contact');
Route::get('artikel', 'UtamaController@artikel');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/tentang', 'HomeController@tentang');

Route::group(['middleware' => ['auth']], function() {
    //admin
	Route::resource('kacamata-admin', 'KacamataController');
	Route::post('/kacamata-post', 'Utama\MessageController@store');
	Route::resource('contactlense_admin', 'ContactLenseController');
	Route::resource('customer', 'CustomerController');
	Route::resource('admin', 'AdminController');
	Route::get('admin-index', 'AdminController@index');
	Route::get('admin-create', 'AdminController@create');
	//Route::post('admin-save', 'AdminController@store');
	Route::post('admin-save', 'RegisterController@store');
});



//ojek
Route::get('/ojek', function () {
    return view('ojek.index');
});

app/Kacamata.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;

class Kacamata extends Model
{
    //`id`, `title`, `desc`, `harga`, `hargadummy`, `deleted_at`, `created_at`, `updated_at`
    
    protected $table = 'kacamata';

    protected $fillable = ['title','desc', 'harga', 'hargadummy' ];

	protected $guarded = ["id"]; 
	public $timestamps = true;
}

app/Http/Controllers/KacamataController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kacamata;

use App\Authorizable;

class KacamataController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kacamata = Kacamata::get();

        return view('ojek.kacamata.index', compact('kacamata'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ojek.kacamata.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $title      = $request->input('title');
        $desc       = $request->input('desc');
        $hargadummy = $request->input('hargadummy');
        
        $harga     = $request->input('harga');
        $gambar     = $request->input('gambar');

        if($request->hasFile('gambar')) {
            $file = $request->file('gambar');
            $date = date('Y-m-d');
            $extension = $file->getClientOriginalExtension();
            $file_name = $gambar. '.' . $extension;
            $destinationPath = 'kacamata';
            $file->move($destinationPath, $file_name );
        }
        
        $upload_file = $file_name;

        $kc             = new Kacamata;
        $kc->title      = $title;
        $kc->desc       = $desc;
        $kc->harga = $harga;
        $kc->hargadummy = $hargadummy;
        $kc->gambar     = $upload_file;
        $kc->save();

        return redirect('kacamata-admin')->with(['update' => 'Data Kacamata sukses di simpan']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/ojek/kacamata/form.blade.php
<div class="form-group">
                  <label>Judul</label>
                  <input type="text" name="title" class="form-control" placeholder="Enter ...">
                </div>
                

                <!-- textarea -->
                <div class="form-group">
                  <label>Deskripsi</label>
                  <textarea class="form-control" name="desc" rows="3" placeholder="Deskripsi"></textarea>
                </div>

                <div class="form-group">
                  <label>Harga</label>
                  <input type="number" name="harga" class="form-control" placeholder="Harga">
                </div>

                <div class="form-group">
                  <label>Harga Strip</label>
                  <input type="number" name="hargadummy" class="form-control" placeholder="Harga Strip">
                </div>

                <div class="form-group">
                  <label>Gambar</label>
                  <input type="file" name="gambar" class="form-control" placeholder="">
                </div>

resources/views/ojek/kacamata/index.blade.php
@extends('layout.admin')

@section('content')

	<!-- breadcumber -->
	<section class="content-header">
      <h1>
        Product
        <small>Kacamata</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Product</a></li>
        <li class="active">Kacamata</li>
      </ol>
    </section>
    <!-- end breadcumber -->

    <section class="content">

    	<div class="row">
    		<div class="col-md-10"></div>
    		<div class="col-md-2">
    			<a class="btn btn-block btn-primary" href="{{route('kacamata-admin.create')}}">Tambah</a>
    		</div>	
    	</div>

    	<div class="row">
    		<div class="col-md-12">
    			<div class="box">
		            
		            <!-- /.box-header -->
		            <div class="box-body">
		              <table id="example" class="table table-bordered table-striped">
		                <thead>
		                <tr>
		                  <th>ID</th>
		                  <th>Title</th>
		                  <th>Desc</th>
		                  <th>Harga</th>
		                  <th>Harga Strip</th>
		                  <th>Gambar</th>
		                  <th>Action</th>
		                </tr>
		                </thead>
		                <tbody>
		                	@foreach($kacamata as $data)
		                <tr>
		                  <td></td>
		                  <td>{{$data->title}}</td>
		                  <td>{{$data->desc}}</td>
		                  <td> {{$data->harga}}</td>
		                  <td>{{$data->hargadummy}}</td>
		                  <td><img src="{{url('/')}}kacamata/{{$data->gambar}}"></td>


		                  	<td></td>
		                </tr>
		                @endforeach
		                
		                </tfoot>
		              </table>
		            </div>
		            <!-- /.box-body -->
		          </div>
		          <!-- /.box -->
    		</div>
    	</div>
    	
    </section>


    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
	
	<script>
	    $(document).ready(function() {
	    $('#example').DataTable();
	    });
	</script>

	<script>
	    $(document).ready(function() {
	    $('#example1').DataTable( {
	        dom: 'Bfrtip',
	        buttons: [
	            'copyHtml5',
	            'excelHtml5',
	            'csvHtml5',
	            'pdfHtml5'
	        ]
	    } );
	} );
	</script>

@endsection

resources/views/ojek/kacamata/new.blade.php
@extends('layout.admin')

	@section('content')

	<!-- breadcumber -->
	<section class="content-header">
      <h1>
        Product
        <small>Kacamata</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Product</a></li>
        <li class="active">Kacamata</li>
      </ol>
    </section>
    <!-- end breadcumber -->

    <section class="content">

    	<!-- general form elements disabled -->
          <div class="box box-warning">
            <div class="box-header with-border">
              <h3 class="box-title">Tambah Kacamata</h3>
            </div>

            <!-- /.box-header -->
            <div class="box-body">

              	<form enctype="multipart/form-data" action="{{ route('kacamata-admin.store') }}" method="POST">

                  <input type="hidden" name="_token" value="{{ csrf_token() }}">

				        <div class="form-group">
                  <label>Judul</label>
                  <input type="text" name="title" class="form-control" placeholder="Judul">
                </div>
                

                <!-- textarea -->
                <div class="form-group">
                  <label>Deskripsi</label>
                  <textarea class="form-control" name="desc" rows="3" placeholder="Deskripsi"></textarea>
                </div>

                <div class="form-group">
                  <label>Harga</label>
                  <input type="number" name="harga" class="form-control" placeholder="Harga">
                </div>

                <div class="form-group">
                  <label>Harga Strip</label>
                  <input type="number" name="hargadummy" class="form-control" placeholder="Harga Strip">
                </div>

                <div class="form-group">
                  <label>Gambar</label>
                  <input type="file" name="gambar" class="form-control" placeholder="">
                </div>

                <div class="box-footer">
	                <button type="submit" class="btn btn-primary">Simpan</button>
	              </div>

                  
              </form>
                <!-- text input -->
                

                
<!-- 
               
                <div class="form-group has-success">
                  <label class="control-label" for="inputSuccess"><i class="fa fa-check"></i> Input with success</label>
                  <input type="text" class="form-control" id="inputSuccess" placeholder="Enter ...">
                  <span class="help-block">Help block with success</span>
                </div>
                <div class="form-group has-warning">
                  <label class="control-label" for="inputWarning"><i class="fa fa-bell-o"></i> Input with
                    warning</label>
                  <input type="text" class="form-control" id="inputWarning" placeholder="Enter ...">
                  <span class="help-block">Help block with warning</span>
                </div>
                <div class="form-group has-error">
                  <label class="control-label" for="inputError"><i class="fa fa-times-circle-o"></i> Input with
                    error</label>
                  <input type="text" class="form-control" id="inputError" placeholder="Enter ...">
                  <span class="help-block">Help block with error</span>
                </div> -->
 
                <!-- checkbox 
                <div class="form-group">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox">
                      Checkbox 1
                    </label>
                  </div>

                  <div class="checkbox">
                    <label>
                      <input type="checkbox">
                      Checkbox 2
                    </label>
                  </div>

                  <div class="checkbox">
                    <label>
                      <input type="checkbox" disabled>
                      Checkbox disabled
                    </label>
                  </div>
                </div>

                <!-- radio 
                <div class="form-group">
                  <div class="radio">
                    <label>
                      <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked>
                      Option one is this and that&mdash;be sure to include why it's great
                    </label>
                  </div>
                  <div class="radio">
                    <label>
                      <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
                      Option two can be something else and selecting it will deselect option one
                    </label>
                  </div>
                  <div class="radio">
                    <label>
                      <input type="radio" name="optionsRadios" id="optionsRadios3" value="option3" disabled>
                      Option three is disabled
                    </label>
                  </div>
                </div> -->

                <!-- select 
                <div class="form-group">
                  <label>Select</label>
                  <select class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                </div>
                <div class="form-group">
                  <label>Select Disabled</label>
                  <select class="form-control" disabled>
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                </div> -->

                <!-- Select multiple
                <div class="form-group">
                  <label>Select Multiple</label>
                  <select multiple class="form-control">
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                </div>
                <div class="form-group">
                  <label>Select Multiple Disabled</label>
                  <select multiple class="form-control" disabled>
                    <option>option 1</option>
                    <option>option 2</option>
                    <option>option 3</option>
                    <option>option 4</option>
                    <option>option 5</option>
                  </select>
                </div> -->

            </div> 
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
    </section>

@endsection